version: "3.7"
services:
  postgres:
    container_name: 'to-do-postgres'
    image: 'postgres'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_DB=to_do'
      - 'POSTGRES_PASSWORD=root'
